spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/luckeymoney?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root

mybatis_config_file: mybatis-config.xml

mapper_path: /mapper/**.xml

entity_package: com.imooc.demo.entity